apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: xiangjieli/scraper
      context: scraper
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: xiangjieli/jobs
      context: jobs
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.go'
            dest: .
    - image: xiangjieli/users
      context: users
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.go'
            dest: .
    # - image: xiangjieli/frontend
    #   context: frontend
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '**/*.js'
    #         dest: .