apiVersion: apps/v1
kind: Deployment
metadata:
  name: applications-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: applications
  template:
    metadata:
      labels:
        app: applications
    spec:
      containers:
        - name: applications
          image: xiangjieli/applications
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key-id
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-default-region
                  key: AWS_DEFAULT_REGION            
            - name: AWS_DEFAULT_OUTPUT
              valueFrom:
                secretKeyRef:
                  name: aws-default-output
                  key: AWS_DEFAULT_OUTPUT

---
apiVersion: v1
kind: Service
metadata:
  name: applications-srv
spec:
  selector:
    app: applications
  ports:
    - name: port-8082
      protocol: TCP
      port: 8082
      targetPort: 8082