apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: xiangjieli/auth

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 8080
      targetPort: 8080




---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv2
spec:
  type: LoadBalancer
  externalIPs:
    - 10.0.0.0
  selector:
    app: auth
  ports:
    - name: port-8080
      protocol: TCP
      port: 8080
      targetPort: 8080