apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
spec:
  rules:
    - host: techcareerhub.dev
      http:
        paths:
          - path: /api/jobs/?(.*)
            backend:
              serviceName: jobs-srv
              servicePort: 8080
          - path: /api/users/?(.*)
            backend:
              serviceName: users-srv
              servicePort: 8081
          - path: /api/applications/?(.*)
            backend:
              serviceName: applications-srv
              servicePort: 8082          
          - path: /api/profiles/?(.*)
            backend:
              serviceName: profiles-srv
              servicePort: 8083
          - path: /api/subscriptions/?(.*)
            backend:
              serviceName: subscriptions-srv
              servicePort: 8084                                      
        #   - path: /?(.*)
        #     backend:
        #       serviceName: frontend-srv
        #       servicePort: 3000