apiVersion: apps/v1
kind: Deployment
metadata:
  name: stat-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: stat
  template:
    metadata:
      labels:
        app: stat
    spec:
      containers:
        - name: stat
          image: xiangjieli/stat
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key-id
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-default-region
                  key: AWS_DEFAULT_REGION            
            - name: AWS_DEFAULT_OUTPUT
              valueFrom:
                secretKeyRef:
                  name: aws-default-output
                  key: AWS_DEFAULT_OUTPUT

---
apiVersion: v1
kind: Service
metadata:
  name: stat-srv
spec:
  selector:
    app: stat
  ports:
    - name: port-8085
      protocol: TCP
      port: 8085
      targetPort: 8085